#pragma once
#include "CoreMinimal.h"
#include "EAchievementsType.generated.h"

UENUM(BlueprintType)
enum class EAchievementsType : uint8 {
    Trophy_Title_00,
    Trophy_Title_01,
    Trophy_Title_02,
    Trophy_Title_03,
    Trophy_Title_04,
    Trophy_Title_05,
    Trophy_Title_06,
    Trophy_Title_07,
    Trophy_Title_08,
    Trophy_Title_09,
    Trophy_Title_10,
    Trophy_Title_11,
    Trophy_Title_12,
    Trophy_Title_13,
    Trophy_Title_14,
    Trophy_Title_15,
    Trophy_Title_16,
    Trophy_Title_17,
    Trophy_Title_18,
    Trophy_Title_19,
    Trophy_Title_20,
    Trophy_Title_21,
    Trophy_Title_22,
    Trophy_Title_23,
    Trophy_Title_24,
    Trophy_Title_25,
    Trophy_Title_26,
    Trophy_Title_27,
    Trophy_Title_28,
    Trophy_Title_29,
    Trophy_Title_30,
    Trophy_Title_31,
    Trophy_Title_32,
    Trophy_Title_33,
    Trophy_Title_34,
    Trophy_Title_35,
    Trophy_Title_36,
    Trophy_Title_37,
    Trophy_Title_38,
    Trophy_Title_39,
    Trophy_Title_40,
    Trophy_Title_41,
    Trophy_Title_42,
    Trophy_Title_43,
    Trophy_Title_44,
    Trophy_Title_45,
    Trophy_Title_46,
    Trophy_Title_47,
    Trophy_Title_48,
    Trophy_Title_49,
    Trophy_Title_50,
    Num,
};

