#pragma once
#include "CoreMinimal.h"
#include "EEffectMode.generated.h"

UENUM(BlueprintType)
enum class EEffectMode : uint8 {
    EFFECT_MODE_CENTER,
    EFFECT_MODE_CENTER_AVERAGE,
    EFFECT_MODE_TOP,
    EFFECT_MODE_BOTTOM,
    EFFECT_MODE_GROUND,
    EFFECT_MODE_DEF_CENTER,
    EFFECT_MODE_TOP_QUARTER,
    EFFECT_MODE_BOTTOM_QUARTER,
    EFFECT_MODE_DEF_CENTER2,
    EFFECT_MODE_DEF_HEAD,
    EFFECT_MODE_DEF_CHEST,
    EFFECT_MODE_DEF_WAIST,
    EFFECT_MODE_SOCKET_CAPSULE,
    EFFECT_MODE_ATK_LHAND,
    EFFECT_MODE_DEF_CHEST_POS,
    EFFECT_MODE_INVALID,
    EFFECT_MODE_MAX UMETA(Hidden),
};

