#pragma once
#include "CoreMinimal.h"
#include "EFairPlayerCameraDebugFlag.generated.h"

UENUM(BlueprintType)
enum class EFairPlayerCameraDebugFlag : uint8 {
    CamModePoint,
    CamModeUcoff,
    AutoReloadDataTable,
    BattleMoveAngleEnable,
    PrintFieldOfView,
    PrintDistanceRecover,
    PrintResetCamera,
    PrintRootOffsetAdjust,
    PrintRootDelay,
    PrintMoveAngleVt,
    PrintMoveAngleHz,
    PrintSlopeAdjust,
    PrintWallAdjust,
    PrintBattleAdjust,
    PrintBattleEventFinish,
    PrintLockOn,
    PrintReturnFocus,
    PrintReturnFocusAttack,
    PrintAttention,
    PrintAttentionTamblin,
    PrintKeepFocus,
    PrintGameCameraLerp,
    PrintPreset,
    PrintAreaPreset,
    PrintSetLocation,
    PrintInputValue,
    PrintBgCheck,
    DrawPspCamera,
    DrawCameraRoot,
    DrawCameraLookAt,
    DrawCameraPos,
    DrawSlopeAdjust,
    DrawWallAdjust,
    DrawBattleEventFinish,
    DrawLockOnChange,
    DrawReturnFocus,
    DrawAttentionLookAt,
    DrawKeepFocus,
    DrawTargetAdjust,
    DrawHeightCheck,
    DrawTransparent,
    DrawAreaPreset,
    DrawExPoint,
    DrawEaseGraph,
    DrawTraceCamRoot,
    DrawTraceCamera,
    DrawTraceCapsule,
    DrawTraceLineMap,
    DrawTraceLineFloor,
    Max,
};

