#pragma once
#include "CoreMinimal.h"
#include "EUIInputButton.generated.h"

UENUM(BlueprintType)
enum class EUIInputButton : uint8 {
    L_Up,
    L_Down,
    L_Left,
    L_Right,
    R_Up,
    R_Down,
    R_Left,
    R_Right,
    L1,
    R1,
    L2,
    R2,
    L3,
    R3,
    Start,
    Select,
    Up,
    Down,
    Left,
    Right,
    PadUp,
    PadDown,
    PadLeft,
    PadRight,
    Decide,
    Cancel,
    Attack,
    Command,
    Command_Move_L,
    Command_Move_R,
    Command_Change_A,
    Command_Change_B,
    Avoid,
    Guard,
    Limit_Activate_A,
    Limit_Activate_B,
    Target_Lock,
    Target_Cange_L,
    Target_Cange_R,
    MouseL,
    MouseR,
    MouseM,
    MouseWUp,
    MouseWDown,
    MateriaOpen,
    MateriaCommand1,
    MateriaCommand2,
    MateriaCommand3,
    MateriaCommand4,
    MateriaCommand5,
    MateriaCommand6,
    ReadySword,
    Dash,
    Num,
};

