#pragma once
#include "CoreMinimal.h"
#include "EUIZOrder.generated.h"

UENUM(BlueprintType)
enum class EUIZOrder : uint8 {
    Picture,
    UnderFilter,
    Event,
    Movie,
    Field,
    GimmickMarker,
    Mail,
    FieldRecovery,
    Warning,
    TargetCursor,
    Number,
    EnemyName,
    ActionNameEM,
    ActionNamePL,
    BattleEscape,
    SkillPower,
    DmwBlackFilter,
    Battle,
    Minigame,
    Compass,
    BattleMes,
    StartEndMes,
    Log,
    DmwMovie,
    DmwHazure,
    Result,
    Subtitle,
    Limit,
    LimitTargetLock,
    Message,
    LimitSkillWin,
    GameOver,
    BattleFilter,
    EffectFilter,
    ActionNameLarge,
    TitleMenu,
    Pause,
    MainMenu,
    Popup,
    ChapterLoading,
    Credits,
    CreditsGuide,
    UpperFilter,
    SkipFilter,
    TopPopup,
    Loading,
    SaveError,
    SystemPopup,
    Num,
    None/* = 0xFF*/,
    Bottom/* = 0x0*/,
    Top/* = 0x2F*/,
    EUIZOrder_MAX/* = 0x100*/,
};

